webapp/posts/models.py
from datetime import datetime
from sqlalchemy.orm import relationship

from webapp.db import db

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    text = db.Column(db.Text, nullable=False)
    created = db.Column(db.DateTime, nullable=False, default=datetime.now())
    user_id = db.Column(
        db.Integer,
        db.ForeignKey('user.id', ondelete='CASCADE'),
        index=True)
    
    user = relationship('User', backref='posts')

    def __repr__(self):
        return '<Post {} {}>'.format(self.title, self.created)

webapp/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import HiddenField, StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError

from webapp.posts.models import Post

class PostForm(FlaskForm):
    post_title =  StringField('Тема', validators=[DataRequired()], render_kw={"class": "form-control"})
    post_text = StringField('Текст поста', validators=[DataRequired()], render_kw={"class": "form-control"})
    submit = SubmitField('Отправить!', render_kw={"class": "btn btn-primary"})

webapp/posts/views.py
from flask import  abort, Blueprint, blueprints, render_template, current_app, flash, redirect, request, url_for
from flask_login import current_user, login_required

from webapp.db import db
from webapp.posts.forms import PostForm
from webapp.posts.models import Post
from webapp.user.models import User
from webapp.utils import get_redirect_target

blueprint = Blueprint('post', __name__, url_prefix='/posts')

@blueprint.route("/")
def post():
    title = 'Посты пользователей'
    post_list = Post.query.filter(Post.text.isnot(None)).order_by(Post.created.desc()).all()
    return render_template('posts/post.html', page_title=title, post_list=post_list)


@blueprint.route('/<int:id>')
def single_post(id):
    my_post = Post.query.filter(Post.id == id).first()
    if not my_post:
        abort(404)
    return render_template('posts/single_post.html', page_title=my_post.title, post=my_post)

@blueprint.route('new_post')
def new_post():
    title = 'Новый пост'
    form = PostForm()
    return render_template('posts/new_post.html', page_title=title, form=form)

@blueprint.route('/add', methods=['POST'])
@login_required
def add_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.post_title.data,text=form.post_text.data, user_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        flash('Пост успешно добавлен')
        return redirect(url_for('post.post'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в заполнении поля "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
    return redirect(get_redirect_target())



@blueprint.route('/<int:id>/delete', methods=['POST', 'GET'])
@login_required
def delete_post(id):
    e = Post.query.filter(Post.id == id).first()
    db.session.delete(e)
    db.session.commit()
    return redirect(url_for('post.post'))

webapp/templates/posts/new_post.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    
    <div class="row">
        <div class="col-4">
            {% include('messages.html') %}
        {% if current_user.is_authenticated %}  
        <form action="{{ url_for('post.add_post') }}" method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.post_title.label }}
                {{ form.post_title() }}
            </div>
            <div class="form-group">
                <label >{{ form.post_text.label }}</label>
                <textarea class="form-control" id="post_text" name="post_text" required type="text" value=""></textarea>
            </div>
            {{ form.submit() }}
        </form>
        {% else %}
        <p><a href="{{ url_for('user.login', next=request.full_path) }}">Авторизуйтесь</a>,
                чтобы добавить пост</p>
        {% endif %}
        </div>
    </div>
</div>
{% endblock %}

webapp/templates/posts/post.html
{% extends "base.html" %}

{% block content %}

  
<div class="container">
  {% include('messages.html') %}
  <div class="row">
    <div class="col-1">
      
    </div>
    <div class="col-8">
    {% if current_user.is_authenticated %}     
      {% for post in post_list %}
      <h3><a href="{{ url_for('post.single_post', id=post.id) }}">{{ post.title }}</a> </h3> 
      
        <h5>
          {% if post.user_id == current_user.id %}
            <a class="action" href="{{ url_for('post.delete_post', id=post.id) }}" method="post">Удалить</a>
          {% endif %}
          <hr />
        </h5>
      {% endfor %}
    {% endif %}
    </div>
    <div class="col-3">
      <a class="nav-link" href="{{ url_for('post.new_post') }}">Добавить новый пост </a>
      
  </div>
  </div>
</div>
  {% endblock %}

webapp/templates/posts/single_post.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        {% include('messages.html') %}
        <div class="col-8 news-content">
            {{ post.text|safe }}
        </div>
    </div>
{% endblock %}